# Generated by Django 3.2.7 on 2021-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer", models.JSONField()),
                ("products", models.JSONField()),
                ("name", models.TextField()),
                ("document", models.CharField(max_length=11)),
                ("total", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                ("date", models.DateTimeField(blank=True)),
                ("qty", models.IntegerField()),
            ],
        ),
    ]
