# Generated by Django 3.2.7 on 2021-09-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashback",
            name="sold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
