# Generated by Django 3.2.7 on 2021-09-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_cashback_sold_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashback",
            name="date",
        ),
        migrations.RemoveField(
            model_name="cashback",
            name="document",
        ),
        migrations.RemoveField(
            model_name="cashback",
            name="name",
        ),
        migrations.RemoveField(
            model_name="cashback",
            name="qty",
        ),
        migrations.RemoveField(
            model_name="cashback",
            name="type",
        ),
        migrations.RemoveField(
            model_name="cashback",
            name="value",
        ),
    ]
