# Generated by Django 2.2.6 on 2021-09-02 18:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuário",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("document", models.CharField(max_length=11)),
                ("total", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("qty", models.IntegerField()),
            ],
        ),
    ]
