# Generated by Django 3.2.7 on 2021-09-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuário",
            name="customer",
            field=models.JSONField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuário",
            name="products",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usuário",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
