# Generated by Django 3.2.7 on 2021-09-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_auto_20210902_2053"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuário",
            name="date",
            field=models.DateTimeField(blank=True),
        ),
    ]
