# Generated by Django 3.2.7 on 2021-09-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_usuário_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuário',
            new_name='Cashback',
        ),
    ]
